### ISSUE TITLE
Mensagem de boas vindas do usuário [5 pts]

### ISSUE THREAD

**Issue by Leocroce** [Leocroce/bookshelf_v1#53]
> Determinar melhorias para mensagem de boas vindas do título do Feed de Noticias.

**Comment by Leocroce** [comment]
Tarefas com referência: 58 #47 Todas estas tarefas fazem referência a este componente.

**Comment by Danielle-29** [comment]
- [ ] Alterado mensagem do feed com mensagem de boas vindas;
- [ ] Cor e alinhamento da mensagem de boas vindas do feed
